import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapters',
      items: [
        'chapters/toolkit/index',
        'chapters/welcome/index',
        {
          type: 'autogenerated',
          dirName: 'chapters/02-semantics',
        },
        {
          type: 'autogenerated',
          dirName: 'chapters/03-navigation',
        },
        {
          type: 'autogenerated',
          dirName: 'chapters/04-visual',
        },
        {
          type: 'autogenerated',
          dirName: 'chapters/05-forms',
        },
        'chapters/motion/index',
        'chapters/live-regions/index',
        'chapters/testing/index',
        'chapters/polish/index',
      ],
    },
  ],
};

export default sidebars;
